[project]
name = "amacoach"
version = "0.1.0"
description = "AmaCoach MCP server for fitness coaching with Claude.ai - workout plans, personal records, and equipment adaptation"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.12.15",
    "mcp>=1.12.4",
]
